#23, Now the app has all the qml code able to be translated
elimu-ai/VoltAir pull request #29
Opened 2017-05-12 18:25 UTC by diegowald

The texts now are translated, and, in case translations is not found a TBT: is prepended to original text.

2017-05-12 18:37 UTC, jo-elimu requested changes

2017-05-12 18:37 UTC, jogrimst commented on VoltAir/qml/ui/LoadingScreen.qml
> +        textElement.text: TR.value("Loading")
@diegowald How does this work? Does the `TR` utility look up a text stored in a text file with the property value "Loading"?

2017-05-13 11:54 UTC, diegowald commented on VoltAir/qml/ui/LoadingScreen.qml
> +        textElement.text: TR.value("Loading")
Hi Jo, 
yes, TR is a class that handles the translations. Internally has a dictionary, which, when invoked the value function, translates the enclosed text.
Currently, if not translated a TBT is preppended. (TBT: To be translated).

2017-05-14 19:53 UTC, jo-elimu requested changes

2017-05-14 19:53 UTC, jogrimst commented on VoltAir/resources/values-Spanish.properties
> +Finish=Fin
@diegowald Change to lower-case property names, e.g. `finish=Fin`

2017-05-14 19:53 UTC, jogrimst commented on VoltAir/resources/values-Spanish.properties
> +Main Menu=Menu Principal
@diegowald Don't use spaces in property names. Change to `main.menu=Menu principal`

2017-05-14 19:53 UTC, jogrimst commented on VoltAir/resources/voltair.qrc
> +        <file>values-Spanish.properties</file>
@diegowald Add English properties file.

2017-05-14 22:35 UTC, diegowald commented on VoltAir/resources/voltair.qrc
> +        <file>values-Spanish.properties</file>
Done!

2017-05-14 22:36 UTC, diegowald commented on VoltAir/resources/voltair.qrc
> +        <file>values-Spanish.properties</file>
Done!

2017-05-15 13:17 UTC, jo-elimu requested changes

2017-05-15 13:17 UTC, jogrimst commented on VoltAir/resources/values-Swahili.properties
> +finish=Fin
@diegowald To make the file easier to translate, change its content from Spanish to English.

2017-05-15 13:47 UTC, jogrimst commented on VoltAir/translations/tr.cpp
>      return _dictionary.contains(key) ? _dictionary[key] : QString("TBT: %1").arg(key);
@diegowald Is this check still necessary now that English is the default fallback language?

2017-05-15 14:44 UTC, merged